### ISSUE TITLE
some code adjustments (for Linux)

### ISSUE THREAD

**Issue by tissatussa** [h1me01/Astra#1]
i managed to compile your source code on Linux, but only after some code changes.
at first cmake complained :

```
CMake Error at CMakeLists.txt:7 (add_executable):
  Cannot find source file:

    src/search/pvTable.h

CMake Error at CMakeLists.txt:7 (add_executable):
  No SOURCES given to target: Astra
```

it seems you're (only) on Windows : the capital 'T' is rejected by Linux, we're case-sensitive here ..

then :

```
/src/datagen.h:31:50: error: ‘INT_MAX’ was not declared in this scope
```

i solved this by adding `#include <climits>` on top of this file, as the compiler message suggested.

then another error :

```
/src/search/../chess/movegen.h:420:23: error: invalid type for parameter 1 of ‘constexpr’ function ‘constexpr int Chess::MoveList::find(Chess::Move) const’
  420 |         constexpr int find(Move m) const {
      |                       ^~~~
```

i can just remove `constexpr` here, and indeed this avoids the error - i used ChatGPT for this ..

then only this warning remains :

```
/src/chess/types.h:110:11: note: ‘Chess::Move’ is not literal because:
  110 |     class Move {
      |           ^~~~
/home/roelof/Apps/Cmake/cmake-3.29.2-linux-x86_64/bin/src/chess/types.h:110:11: note:   ‘Chess::Move’ is not an aggregate, does not have a trivial default constructor, and has no ‘constexpr’ constructor that is not a copy or move constructor
```

you might solve that also ..
(all this happens with both 2.0 and 2.1)

Astra runs fine in CuteChess GUI !

**Comment by h1me01** [comment]
Thanks! Yes, initially I only tested it on windows (also didn't want to bother with linux yet). I will look into it and might support linux properly later on.

**Comment by tissatussa** [comment]
i think those adjustments will also (still) work on Windows .. i can test any new version for you. Is some minimal cmake version needed ? I often encounter that, then you should mention it in README and/or fail gracefully by a message.

**Comment by h1me01** [comment]
I've tested it, and it works fine on Windows. I'll also update the README with more detailed instructions on compiling the source code yourself and include a Makefile. The minimum CMake version required is 3.28.

**Comment by tissatussa** [comment]
a good Makefile is fine .. and recently i discovered the Meson Build System, like cmake and make but much nicer, i created some template which should compile all (mainly C) packages, regardless their structure - but i'm far from that yet, the docs are awkward .. Meson is great though, read some reviews.

**Comment by h1me01** [comment]
Interesting, this is the first time I've heard about Meson. If it works well to compile such projects easily, then that's awesome. Thanks for sharing the info!

**Comment by tissatussa** [comment]
> ..If it works well to compile such projects easily..

your code tree is simple, but it can more complex / bigger ones .. its script language is clean and simple like python .. do much with only one line .. complete install menus are possible, colors and more .. detect avx / bmi etc. and auto-set those etc. Made by someone who also struggled with cmake / make and their syntax & setup .. i can send you my template with short expl

**Comment by h1me01** [comment]
That would be great! Where could you send it to me?

**Comment by tissatussa** [comment]
this is the file `meson.build` in the project root :

```
project(
  'depends_on_mode',  # project name will be corrected
	'cpp',
  default_options: [
    'cpp_std=c++11',

    # 'warning_level=0',
    'warning_level=3',

    # ### not needed, auto set when buildtype given
    # 'optimization=0',
    # 'optimization=3',

    # 'buildtype=debug',
    'buildtype=release',

    'default_library=shared'
    # 'default_library=static'
  ]
)

exe_name = 'mytest'
files = [
  'mytest.cpp'
]

cc = meson.get_compiler('cpp')

target = target_machine.cpu_family()
if (target != 'riscv64')
  add_project_arguments('-march=native', language: 'cpp')
endif

if cc.has_argument('-mavx2')
  add_project_arguments('-mavx2', language: 'cpp')
endif

if cc.has_argument('-mbmi2')
  add_project_arguments('-mbmi2', language: 'cpp')
endif

add_project_arguments('-DALLOW_EXPERIMENTAL_API', language: 'cpp')
add_project_arguments('-D_GNU_SOURCE', language: 'cpp')

# enable extra warnings and disable any unwanted warnings
warning_flags = [
  '-Wno-pedantic',
  '-Wno-format-truncation'
]
foreach arg: warning_flags
  if cc.has_argument(arg)
    add_project_arguments(arg, language: 'cpp')
  endif
endforeach

exe = executable(
  exe_name,
  files,
  install : false
)

# move_binary = custom_target(
#   output : 'binary',  # internal reference name of the output
#   input : exe,  # reference to the executable
#   command : ['mv', exe.full_path(), meson.source_root()],
#   build_by_default : true
# )
```

you should adjust only a few things, probably only 1 : the `files` list can hold not only one but many, seperated by comma's. And you should have Python, Meson and Ninja installed on your OS, see https://github.com/mesonbuild/meson .. i'm far from an Meson expert yet, i hope my 'template' works for you. Read about Meson, YT videos exist too ..

**Comment by tissatussa** [comment]
in fact this can be the only Meson file of your project .. although i find constructs which have a `meson.build` file in a (sub)folder also .. don't know how this works or if it's needed .. as you see, its syntax is simple and nice.

**Comment by h1me01** [comment]
Thanks again for all the work you put in! I’ll definitely look into it.
